name: Docker Image CI

on:
  push:
    branches: ["main"]   # or "master" depending on your repo
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: fitz94/auth_service-web:latest
